// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nutrition_planner.Data;

#nullable disable

namespace nutrition_planner.Migrations
{
    [DbContext(typeof(FoodModelContext))]
    partial class FoodModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("food_schema")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("nutrition_planner.Models.FoodModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<double?>("CalculatedMass")
                        .HasColumnType("float(2)");

                    b.Property<double?>("Carbohydrate")
                        .HasColumnType("float(2)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Fat")
                        .HasColumnType("float(2)");

                    b.Property<double?>("Kilocalories")
                        .HasColumnType("float(2)");

                    b.Property<double?>("Protein")
                        .HasColumnType("float(2)");

                    b.Property<double?>("Sugar")
                        .HasColumnType("float(2)");

                    b.Property<double?>("Water")
                        .HasColumnType("float(2)");

                    b.HasKey("ID");

                    b.ToTable("food_table", "food_schema");
                });
#pragma warning restore 612, 618
        }
    }
}
